<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#arithmetic operators
a=10
b=30
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)


#comparison operators
print(a<=b)
print(a>=b)
print(a==b)
print(a!=b)
print(a>b)
print(a<b)


x = True
y = False
#logical operators
print(x and y)
print(x or y)
print(not x)


c = 5
d = 3
#bitwise operators
print(c & d)
print(c | d)
print(c ^ d)
print(~c)
print(c >> 1)
print(c << 1)






40
-20
300
0.3333333333333333
0
10
1000000000000000000000000000000
True
False
False
True
False
True
False
True
False
1
7
6
-6
2
10


In [ ]:

#matrix operations with numpy
import  numpy as np

#creating matrices
mat1 = np.array([[1,2],[4,5]])
mat2 = np.array([[7,8],[10,11]])
print("Matrix 1")
print(mat1)
print("\n")
print("Matrix 2")
print(mat2)

print("\n")
#matrix addition
print("addition")
mat_addition = mat1+mat2
print(mat_addition)

#matrix multiplication
print("multiplication")
mat_multiply = np.matmul(mat1,mat2)
print(mat_multiply)

#matrix transpose
print("transpose")
mat_transpose = np.transpose(mat1)
print(mat_transpose)

#creating a numpy matrix
mat_random = np.array(matrix)

#scalar multiplication
print("scalar multiplication")
mat_scalar = mat1*3
print(mat_scalar)





Matrix 1
[[1 2]
 [4 5]]


Matrix 2
[[ 7  8]
 [10 11]]


addition
[[ 8 10]
 [14 16]]
multiplication
[[27 30]
 [78 87]]
transpose
[[1 4]
 [2 5]]


NameError: name 'matrix' is not defined

In [ ]:
#lambda operator

floc = lambda f:(f-32)*5.0/9
print(floc(5))


-15.0


In [ ]:
#accepting user input
a = int(input("enter num 1 : "))
b = int(input("enter num 2 : "))

c = a + b
print("sum = ",c)

enter num 1 : 1
enter num 2 : 2
sum =  3


Problem 1 - get basic pay from the user and calculate da (80% of basic pay) , hra (30% of basic pay)

In [ ]:
a = float(input("enter basic pay : "))
da = a*0.8
hra = a*0.3
print("da = ",da)
print("hra = ",hra)

enter basic pay : 1000
da =  800.0
hra =  300.0
