<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics_9(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#numpy
#example

import numpy as np
import sys

a = list(range(100000))
print(sys.getsizeof(100000)*len(a))
b = np.arange(100000)
print(b.size*b.itemsize)


2800000
800000


In [14]:
#NumPy arrays are faster than lists

import time as t

t1 = t.time()
a = range(100000)
b = range(100000)
z = [a[i]+ b[i] for i in range(len(a))]
print(t.time() - t1)

#using numpy
import numpy as np
import time as t

t1 = t.time()
a = np.arange(100000)
b = np.arange(100000)
z = a+b
print(t.time() - t1)



0.03230118751525879
0.0029523372650146484


In [21]:
#creating a numpy array

#1-D array
a = np.array([1,2,3])
b = np.array([(1,2,3)]) #another way
print(a)
print("\n",b)

#2-D array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([(1,2,3),(4,5,6)]) #another way
print("\n",a)
print("\n",b)
print(a.ndim) #prints the dimension
print(a.shape)
print(a[1][2]) #a[rows][cols]



[1 2 3]

 [[1 2 3]]

 [[1 2 3]
 [4 5 6]]

 [[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [25]:
#3-D array

a = np.array([
              [(1,2,3),(4,5,6),(7,8,9)],
              [(1,2,3),(4,5,6),(7,8,9)],
              [(1,2,3),(4,5,6),(7,8,10)],
              ])

print(a)
print("\n",a.shape)
print(a.ndim)
print(a[2][2][2])
print(a[2,2,2])#another way to access elements

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8 10]]]

 (3, 3, 3)
3
10
10
