<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics_9(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#numpy
#example

import numpy as np
import sys

a = list(range(100000))
print(sys.getsizeof(100000)*len(a))
b = np.arange(100000)
print(b.size*b.itemsize)


2800000
800000


In [14]:
#NumPy arrays are faster than lists

import time as t

t1 = t.time()
a = range(100000)
b = range(100000)
z = [a[i]+ b[i] for i in range(len(a))]
print(t.time() - t1)

#using numpy
import numpy as np
import time as t

t1 = t.time()
a = np.arange(100000)
b = np.arange(100000)
z = a+b
print(t.time() - t1)



0.03230118751525879
0.0029523372650146484


In [21]:
#creating a numpy array

#1-D array
a = np.array([1,2,3])
b = np.array([(1,2,3)]) #another way
print(a)
print("\n",b)

#2-D array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([(1,2,3),(4,5,6)]) #another way
print("\n",a)
print("\n",b)
print(a.ndim) #prints the dimension
print(a.shape)
print(a[1][2]) #a[rows][cols]



[1 2 3]

 [[1 2 3]]

 [[1 2 3]
 [4 5 6]]

 [[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [26]:
#3-D array

a = np.array([
              [(1,2,3),(4,5,6),(7,8,9)],
              [(1,2,3),(4,5,6),(7,8,9)],
              [(1,2,3),(4,5,6),(7,8,10)],
              ])

print(a)
print("\n",a.shape)
print(a.ndim)
print(a.size) #prints total number of arrays
print(a.itemsize) #prints total number elements in the array
print(a[2][2][2])
print(a[2,2,2])#another way to access elements

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8 10]]]

 (3, 3, 3)
3
27
8
10
10


In [31]:
#Reshaping anarray in numpy
a = np.arange(25)
print(a)

#reshaping
b = a.reshape(5,5)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [38]:
#Ravel a 2D array
#used to get 1D array from 2D array

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.ravel() #converts the 2D array(a) into  1D array
#or b = np.ravel(a) => this also works
print(b)

#flatten() => same function as ravel
a = np.array([[1,2,3],[4,5,6]])
print("\n",a)
b = a.flatten() #converts the 2D array(a) into  1D array
print(b)

#Reshape => same function as ravel
a = np.array([[1,2,3],[4,5,6]])
print("\n",a)
b = a.reshape(-1) #converts the 2D array(a) into  1D array
print(b)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

 [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

 [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [44]:
#Slicing in Numpy
a = np.arange(0,36).reshape(6,6)
print(a)

s = a[3:6,1:4] #a[row_start:row_end,coln_start,coln_end]
print("\n",s)

#Note: end is always n-1

t = a[1:,3:]
print("\n",t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

 [[19 20 21]
 [25 26 27]
 [31 32 33]]

 [[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]


In [45]:
#Built-in Methods

#odd numbers from 101 to 130
a = np.arange(101,130,0.7) #this 0.7 is step value (ie) a(start,end,step)
print(a)

[101.  101.7 102.4 103.1 103.8 104.5 105.2 105.9 106.6 107.3 108.  108.7
 109.4 110.1 110.8 111.5 112.2 112.9 113.6 114.3 115.  115.7 116.4 117.1
 117.8 118.5 119.2 119.9 120.6 121.3 122.  122.7 123.4 124.1 124.8 125.5
 126.2 126.9 127.6 128.3 129.  129.7]
