<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics_11(NumPy-3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Linear Algebra (numpy.linalg)

import numpy as n

a = n.matrix('1,2,3;5,6,7;4,7,8')
print(a)

print(a.size)
print(a.itemsize)
print(a.dtype)

#finding determinant
det = n.linalg.det(a)
print(det)

#finding rank
rank = n.linalg.matrix_rank(a)
print(rank)

[[1 2 3]
 [5 6 7]
 [4 7 8]]
9
8
int64
7.999999999999995
3


In [12]:
#Solving linaar equations

#3x+2y+3z = 1, 2x-3y+z = 2, 4x+8y+5z = 2
a = n.matrix('3,2,3;2,-3,1;4,8,5')
b = n.matrix('1;2;2')

c = n.linalg.solve(a,b)
print("Solution:\n",c)

Solution:
 [[  9.]
 [  2.]
 [-10.]]


In [20]:
#Qr decomposition
a = n.matrix('1,2,3;5,6,7;4,7,8')
q ,r = n.linalg.qr(a) #q => orthogonal matrix and r => upper triangle matrix
print(q)
print("\n",r)
print(r.dtype)
print("\n",r.astype(int))


[[-0.15430335  0.31524416 -0.93638218]
 [-0.77151675 -0.63048832 -0.08512565]
 [-0.6172134   0.70929937  0.34050261]]

 [[ -6.4807407   -9.258201   -10.8012345 ]
 [  0.           1.81265393   2.20670914]
 [  0.           0.          -0.68100522]]
float64

 [[ -6  -9 -10]
 [  0   1   2]
 [  0   0   0]]


In [22]:
#Single Valued Decomposition (SVD)

a = n.random.randn(1,9)
print(a)

u,s,vh = n.linalg.svd(a)
print(u)
print(s)
print(vh)


[[ 1.70562301 -0.38116991  1.47988677 -0.8936861   2.45559395 -0.16488234
  -0.42694606  0.17469476  1.28459918]]
[[-1.]]
[3.73675048]
[[-0.45644552  0.10200572 -0.39603575  0.2391613  -0.65714689  0.04412452
   0.11425597 -0.04675045 -0.34377441]
 [ 0.10200572  0.99285578  0.02773733 -0.01675025  0.04602489 -0.00309037
  -0.0080022   0.00327428  0.02407708]
 [-0.39603575  0.02773733  0.89231021  0.06503259 -0.17869097  0.01199831
   0.03106841 -0.01271235 -0.09347892]
 [ 0.2391613  -0.01675025  0.06503259  0.96072759  0.10790936 -0.00724564
  -0.01876185  0.00767684  0.05645081]
 [-0.65714689  0.04602489 -0.17869097  0.10790936  0.70349592  0.01990895
   0.05155219 -0.02109376 -0.1551107 ]
 [ 0.04412452 -0.00309037  0.01199831 -0.00724564  0.01990895  0.9986632
  -0.0034615   0.00141635  0.010415  ]
 [ 0.11425597 -0.0080022   0.03106841 -0.01876185  0.05155219 -0.0034615
   0.99103679  0.0036675   0.02696859]
 [-0.04675045  0.00327428 -0.01271235  0.00767684 -0.02109376  0.00141635
  

In [23]:
#Compute eigen values

a = n.matrix('1,2,3;5,6,7;4,7,8')
eig = n.linalg.eigvals(a)
print(eig)

[15.60940882+0.j         -0.30470441+0.64781681j -0.30470441-0.64781681j]


In [24]:
#Eigen Value Decomposition

a = n.matrix('1,2,3;5,6,7;4,7,8')
w , v = n.linalg.eig(a)
print(w) #w => eigen values
print(v) #v => eigen vectors

[15.60940882+0.j         -0.30470441+0.64781681j -0.30470441-0.64781681j]
[[ 0.23725269+0.j          0.25506239-0.42921184j  0.25506239+0.42921184j]
 [ 0.64960993+0.j         -0.70059909+0.j         -0.70059909-0.j        ]
 [ 0.72230056+0.j          0.4488226 +0.24174276j  0.4488226 -0.24174276j]]


In [26]:
#Compute the trace and determinant
#Note :- trace() is not a function of linear algebra (linalg())

a = n.matrix('1,2,3;5,6,7;4,7,8')
print(n.trace(a))

15


In [28]:
#Inverse/Pseudo Inverse of a matrix

# inv() => works with non singular matrix alone and doesnot involve floating point arithmetic
a = n.matrix('1,2,3;5,6,7;4,7,8')
inv = n.linalg.inv(a)
print(inv)

# pinv() => works with non singular as well as singular matrix alone and
#does involve floating point arithmetic
pinv = n.linalg.pinv(a)
print(pinv)

[[-0.125  0.625 -0.5  ]
 [-1.5   -0.5    1.   ]
 [ 1.375  0.125 -0.5  ]]
[[-0.125  0.625 -0.5  ]
 [-1.5   -0.5    1.   ]
 [ 1.375  0.125 -0.5  ]]


In [30]:
#Solve a linear system
# solve a linear system in closed form

a = n.matrix('1,2,3;5,6,7;4,7,8')
y = [1,2,3]

c = n.linalg.solve(a,y)
print(c)

[-0.375  0.5    0.125]


In [29]:
#calculate least squares solution

a = n.matrix('1,2,3;5,6,7;4,7,8')
y = [1,2,4]
soln,residuals,rank,singular = n.linalg.lstsq(a,y)
print(soln)
print(residuals)
print(rank)
print(singular)

[-0.875  1.5   -0.375]
[]
3
[15.85540833  1.19486952  0.42227179]


<ipython-input-29-4d4951771b54>:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  soln,residuals,rank,singular = n.linalg.lstsq(a,y)


In [38]:
#Manipulating matrices
mat1 = n.matrix('5,6,2;4,7,19;0,3,12')
print("mat1:\n",mat1)

mat2 = n.matrix('14,-2,12;4,4,5;5,5,1')
print("\nmat2:\n",mat2)

#Scalar multiplication
print("\n",5*mat1)

print("\n",mat1**3)

print("\n",mat1-mat2)
print("\n",mat1+mat2)

mat1:
 [[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]

mat2:
 [[14 -2 12]
 [ 4  4  5]
 [ 5  5  1]]

 [[25 30 10]
 [20 35 95]
 [ 0 15 60]]

 [[ 557 1284 3356]
 [ 760 2305 6994]
 [ 288 1074 3519]]

 [[ -9   8 -10]
 [  0   3  14]
 [ -5  -2  11]]

 [[19  4 14]
 [ 8 11 24]
 [ 5  8 13]]


In [42]:
#Exercise - compute A**2 -2A +3

A = n.matrix('1,-1;2,1')
print(A)

res = A**2 - (2*A)+3
print("\n",res)

[[ 1 -1]
 [ 2  1]]

 [[0 3]
 [3 0]]


In [51]:
#Exercise Ax = b

A = n.matrix('5,6,2;4,7,19;0,3,12')
print(A)

b = n.matrix('-1;2;1')
print("\n",b)

x = n.linalg.solve(A,b)
print("\n",x)

print("\n",A*x)

[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]

 [[-1]
 [ 2]
 [ 1]]

 [[ 0.45736434]
 [-0.62790698]
 [ 0.24031008]]

 [[-1.]
 [ 2.]
 [ 1.]]


In [52]:
#Exercise Bx = b

B = n.matrix('5,6,2;4,7,19;0,3,12')
print(B)

b = n.matrix('4;5;6')
print("\n",b)

x = n.linalg.solve(B,b)
print("\n",x)

print("\n",B*x)

[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]

 [[4]
 [5]
 [6]]

 [[-2.93023256]
 [ 3.20930233]
 [-0.30232558]]

 [[4.]
 [5.]
 [6.]]


In [53]:
#exercise A**-1 A = 1

A = n.matrix('5,6,2;4,7,19;0,3,12')
print(A)

Ainv = n.linalg.inv(A)
print("\n",Ainv)

print("\n",A*Ainv)


[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]

 [[-0.20930233  0.51162791 -0.7751938 ]
 [ 0.37209302 -0.46511628  0.6744186 ]
 [-0.09302326  0.11627907 -0.08527132]]

 [[ 1.00000000e+00  4.99600361e-16 -4.71844785e-16]
 [ 1.38777878e-16  1.00000000e+00 -2.63677968e-16]
 [ 1.11022302e-16  1.11022302e-16  1.00000000e+00]]


In [56]:
#Exercise => solve the system of equations

# x+y+z = 9, 2x-y+z = 5, 4x+y-z = 7

A = n.matrix('1,1,1;2,-1,1;4,1,-1')
print(A)

b = n.matrix('9;5;7')
print("\n",b)

res = n.linalg.solve(A,b)
print("\n",res)

print("\n",A*res)

[[ 1  1  1]
 [ 2 -1  1]
 [ 4  1 -1]]

 [[9]
 [5]
 [7]]

 [[2.]
 [3.]
 [4.]]

 [[9.]
 [5.]
 [7.]]


In [68]:
#Exercise => solve the system of equations
# 2x+y+2z = 0, 2x-y+z = 10, x+3y-z = 5

A = n.array([(2,1,2),(2,-1,1),(1,3,-1)])
print(A)

b = n.matrix([
            [(0)],
             [(10)],
              [(5)]
            ])
print("\n",b)

c = n.linalg.solve(A,b)
print("\n",c)

print("\n",A*c)

[[ 2  1  2]
 [ 2 -1  1]
 [ 1  3 -1]]

 [[ 0]
 [10]
 [ 5]]

 [[ 6.53846154]
 [-2.30769231]
 [-5.38461538]]

 [[1.77635684e-15]
 [1.00000000e+01]
 [5.00000000e+00]]


In [59]:
#Exercise least squares
A = n.matrix('0,1;1,1;2,1')
print(A)

b = n.matrix('6;0;0')
print("\n",b)

soln,residuals,rank,singular = n.linalg.lstsq(A,b)
print("\n",soln)
print("\n",residuals)
print("\n",rank)
print("\n",singular)


[[0 1]
 [1 1]
 [2 1]]

 [[6]
 [0]
 [0]]

 [[-3.]
 [ 5.]]

 [[6.]]

 2

 [2.6762432  0.91527173]


<ipython-input-59-6e72e111c227>:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  soln,residuals,rank,singular = n.linalg.lstsq(A,b)


In [69]:
#Exercise => solve the system of equations

# x-y+z = 4, 2x+y-3z = 0, x+y-z = 2

A = n.matrix('1,-1,1;2,1,-3;1,1,-1')
print(A)

b = n.matrix('4;0;2')
print("\n",b)

res = n.linalg.solve(A,b)
print("\n",res)

print("\n",A*res)

[[ 1 -1  1]
 [ 2  1 -3]
 [ 1  1 -1]]

 [[4]
 [0]
 [2]]

 [[3. ]
 [1.5]
 [2.5]]

 [[4.0000000e+00]
 [4.4408921e-16]
 [2.0000000e+00]]
