<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#arithmetic operators
a=10
b=30
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)


#comparison operators
print(a<=b)
print(a>=b)
print(a==b)
print(a!=b)
print(a>b)
print(a<b)


x = True
y = False
#logical operators
print(x and y)
print(x or y)
print(not x)


c = 5
d = 3
#bitwise operators
print(c & d)
print(c | d)
print(c ^ d)
print(~c)
print(c >> 1)
print(c << 1)






40
-20
300
0.3333333333333333
0
10
1000000000000000000000000000000
True
False
False
True
False
True
False
True
False
1
7
6
-6
2
10


In [ ]:

#matrix operations with numpy
import  numpy as np

#creating matrices
matrix = np.array([[1,2],[4,5]])
mat1 = np.array([[7,8],[10,11]])
print("Matrix 1")
print(matrix)
print("\n")
print("Matrix 2")
print(mat1)

print("\n")
#matrix addition
print("addition")
mat_addition = matrix+mat1
print(mat_addition)

#matrix multiplication
print("\nmultiplication")
mat_multiply = np.matmul(matrix,mat1)
print(mat_multiply)

#matrix transpose
print("\ntranspose")
mat_transpose = np.transpose(matrix)
print(mat_transpose)

#creating a numpy matrix
print("random matrix")
mat_random = np.array(matrix)
print("\n",mat_random)

#matrix subtraction
print("\nsubtraction")
mat_subtraction = matrix-mat1
print(mat_subtraction)

#scalar multiplication
print("\nscalar multiplication")
mat_scalar = mat1*3
print(mat_scalar)





Matrix 1
[[1 2]
 [4 5]]


Matrix 2
[[ 7  8]
 [10 11]]


addition
[[ 8 10]
 [14 16]]

multiplication
[[27 30]
 [78 87]]

transpose
[[1 4]
 [2 5]]
random matrix

 [[1 2]
 [4 5]]

subtraction
[[-6 -6]
 [-6 -6]]

scalar multiplication
[[21 24]
 [30 33]]


In [ ]:
#lambda operator

floc = lambda f:(f-32)*5.0/9
print(floc(5))


-15.0


In [ ]:
#accepting user input
a = int(input("enter num 1 : "))
b = int(input("enter num 2 : "))

c = a + b
print("sum = ",c)

enter num 1 : 1
enter num 2 : 2
sum =  3


Problem 1 - get basic pay from the user and calculate da (80% of basic pay) , hra (30% of basic pay)

In [ ]:
a = float(input("enter basic pay : "))
da = a*0.8
hra = a*0.3
print("da = ",da)
print("hra = ",hra)

enter basic pay : 1000
da =  800.0
hra =  300.0


In [ ]:
# Type conversions

#Float

# Integer to Float

# float(int_var) => converts int to float

#eg
a = 1
print(a)
print(float(a)) # float conversion

# Complex

# complex(real , image) => converts to complex

#eg
r = 1
img = 2
print(complex(r,img))


# Integer to String

# str(int_var) => converts int to string

#eg
a = 1
b = str(1)
print(typr(b))

# vice-versa and also Float to Integer

# int(str_var) => converts string to int

a = '1'
b = int(a)
print(type(b))



