<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics_21(Data%20Transformation%20with%20Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Data Transformation using Pandas

#Pandas DataFrame.transform()

#Syntax => DataFrame.transform(func , axis = 0, *args, **kwargs)

import pandas as pd


df = pd.DataFrame({
    'A' : [12,4,5,None,1],
    'B' : [7,2,54,3,None],
    'C' : [20,16,11,3,8],
    'D' : [14,3,None,2,6],
}, index = range(5))


df

A     B   C     D
0  12.0   7.0  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  11   NaN
3   NaN   3.0   3   2.0
4   1.0   NaN   8   6.0

In [5]:
res = df.transform(func = lambda x : x + 10)
res

A     B   C     D
0  22.0  17.0  30  24.0
1  14.0  12.0  26  13.0
2  15.0  64.0  21   NaN
3   NaN  13.0  13  12.0
4  11.0   NaN  18  16.0

In [6]:
res = df.transform(func = ['sqrt','exp'])
res

A                        B                       C                \
       sqrt            exp      sqrt           exp      sqrt           exp   
0  3.464102  162754.791419  2.645751  1.096633e+03  4.472136  4.851652e+08   
1  2.000000      54.598150  1.414214  7.389056e+00  4.000000  8.886111e+06   
2  2.236068     148.413159  7.348469  2.830753e+23  3.316625  5.987414e+04   
3       NaN            NaN  1.732051  2.008554e+01  1.732051  2.008554e+01   
4  1.000000       2.718282       NaN           NaN  2.828427  2.980958e+03   

          D                
       sqrt           exp  
0  3.741657  1.202604e+06  
1  1.732051  2.008554e+01  
2       NaN           NaN  
3  1.414214  7.389056e+00  
4  2.449490  4.034288e+02

In [8]:
#Other Data Transformation

# 1) Finding Dulplicate values

df1 = pd.DataFrame({
    'a':['one','two']*3,
    'b':[1,1,2,3,2,3]
}, index = range(6))

df1

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [13]:
df1.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [14]:
#To drop the duplicates

df1.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [15]:
df1['c'] = range(6)
df1

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [18]:
df1.duplicated(['a','b'], keep = 'last')

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [24]:
# 2) Mapping

df2 = pd.DataFrame({
    'names' : ['tim','tom', 'sam', 'kate', 'kim', 'tony'],
    'scores' : [60,50,70,80,40,30]
})

df2


names  scores
0   tim      60
1   tom      50
2   sam      70
3  kate      80
4   kim      40
5  tony      30

In [34]:
classes = {'tim' : 'A', 'tom' : 'A', 'sam' : 'A', 'kate' : 'B', 'kim' : 'B', 'tony' : 'B'}
classes

{'tim': 'A', 'tom': 'A', 'sam': 'A', 'kate': 'B', 'kim': 'B', 'tony': 'B'}

In [35]:
n = df2['names'].str.capitalize()
n

0     Tim
1     Tom
2     Sam
3    Kate
4     Kim
5    Tony
Name: names, dtype: object

In [37]:
df2['branches'] = df2['names'].map(classes)
df2

names  scores branches
0   tim      60        A
1   tom      50        A
2   sam      70        A
3  kate      80        B
4   kim      40        B
5  tony      30        B

In [38]:
# 3) Replace

s = pd.Series([10,20,30,40])
s


0    10
1    20
2    30
3    40
dtype: int64

In [40]:
import numpy as np

a = s.replace(20, np.nan)
a

0    10.0
1     NaN
2    30.0
3    40.0
dtype: float64

In [42]:
b = s.replace([10,40,30],[0,0,np.nan])
b

0     0.0
1    20.0
2     NaN
3     0.0
dtype: float64

In [44]:
c = s.replace({ 20 : np.nan, 30 : 40})
c

0    10.0
1     NaN
2    40.0
3    40.0
dtype: float64

In [47]:
# 4) Renaming

df4 = pd.DataFrame(np.arange(12).reshape(3,4), columns = ['A','B','C','D'])

s = pd.Series(['one','two','three'])
df4.index = df4.index.map(s)

df4


A  B   C   D
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [50]:
r = df4.rename(index = str.title, columns = str.lower)
r

a  b   c   d
One    0  1   2   3
Two    4  5   6   7
Three  8  9  10  11

In [60]:
t = df4.rename(index = { 'one' : 1, 'two' : 2, 'three' : 3}, columns = {'A' : 1, 'B' : 2, 'C' : 3, 'D' : 4})
t

1  2   3   4
1  0  1   2   3
2  4  5   6   7
3  8  9  10  11

In [59]:
# 5) cutting

sc = [30,80,40,90,60,45,95,75,55,100,65,85]
sc

[30, 80, 40, 90, 60, 45, 95, 75, 55, 100, 65, 85]

In [61]:
x = [20,40,60,80,100]
x

[20, 40, 60, 80, 100]

In [62]:
y =  pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [63]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [64]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [66]:
pd.Series(y).value_counts()

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [67]:
z = pd.cut(sc,x,right = False)
z

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [68]:
name = ['low','medium','high','very high']
pd.cut(sc,x, labels = name)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [69]:
pd.cut(sc, 10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] <
                                            (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] <
                                            (86.0, 93.0] < (93.0, 100.0]]

In [71]:
#qcut => quater cut

data = np.random.randn(100)
c = pd.qcut(data,4)
c

[(0.0766, 0.813], (0.813, 2.846], (-0.448, 0.0766], (-0.448, 0.0766], (-0.448, 0.0766], ..., (-2.149, -0.448], (0.813, 2.846], (-0.448, 0.0766], (0.813, 2.846], (-0.448, 0.0766]]
Length: 100
Categories (4, interval[float64, right]): [(-2.149, -0.448] < (-0.448, 0.0766] < (0.0766, 0.813] <
                                           (0.813, 2.846]]

In [72]:
pd.Series(c).value_counts()

(-2.149, -0.448]    25
(-0.448, 0.0766]    25
(0.0766, 0.813]     25
(0.813, 2.846]      25
Name: count, dtype: int64

In [73]:
# 6) Findng the specific values in a dataset


data1 = pd.DataFrame(np.random.randn(1000,4))
data1

0         1         2         3
0   -0.974441 -0.922844  1.247595 -1.087690
1    1.493794 -1.697234  1.192316 -0.162016
2    2.317597  1.013652  0.422282 -0.488483
3   -0.864920 -1.212508  0.994134  1.547242
4    0.887101  0.501831  0.433488 -0.633134
..        ...       ...       ...       ...
995  0.413593  0.600808  2.001807  1.569607
996  0.721871 -0.377488 -0.664640  0.692729
997  1.106186  0.181453 -1.544455 -0.793675
998  0.188927  0.593170  0.359808 -0.342639
999 -0.460756  0.377386  0.668697 -0.760581

[1000 rows x 4 columns]

In [74]:
col = data1[1]
col

0     -0.922844
1     -1.697234
2      1.013652
3     -1.212508
4      0.501831
         ...   
995    0.600808
996   -0.377488
997    0.181453
998    0.593170
999    0.377386
Name: 1, Length: 1000, dtype: float64

In [76]:
col[np.abs(col)>3]

525   -3.725015
617   -3.291700
Name: 1, dtype: float64

In [82]:
# 7) Selecting

df5 = pd.DataFrame(np.arange(12).reshape(4,3))
df5

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [86]:
rr = np.random.permutation(4)
rr

array([2, 3, 0, 1])

In [87]:
df5.take(rr)

0   1   2
2  6   7   8
3  9  10  11
0  0   1   2
1  3   4   5

In [88]:
df5.sample() #To select a row randomly

0   1   2
3  9  10  11

In [89]:
df5.sample(n=3)

0   1   2
0  0   1   2
1  3   4   5
3  9  10  11

In [90]:
# 8) Converta Categorical Data into a Dummy Variables

df6 = pd.DataFrame({
    'letter' : ['c','b','a','b','b','a'],
    'number' : [0,1,2,3,4,5]
})

df6



letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [92]:
pd.get_dummies(df6['letter'])

a      b      c
0  False  False   True
1  False   True  False
2   True  False  False
3  False   True  False
4  False   True  False
5   True  False  False

In [93]:
data3 = np.random.randn(10)
data3

array([-0.12330903,  1.65092073, -0.35836824, -0.60644687, -0.55227916,
       -0.56265594,  0.95370008,  1.21956849,  0.70707087,  0.0881132 ])

In [95]:
u = pd.cut(data3,4)
u

[(-0.609, -0.0421], (1.087, 1.651], (-0.609, -0.0421], (-0.609, -0.0421], (-0.609, -0.0421], (-0.609, -0.0421], (0.522, 1.087], (1.087, 1.651], (0.522, 1.087], (-0.0421, 0.522]]
Categories (4, interval[float64, right]): [(-0.609, -0.0421] < (-0.0421, 0.522] < (0.522, 1.087] <
                                           (1.087, 1.651]]

In [96]:
pd.get_dummies(u)

(-0.609, -0.0421]  (-0.0421, 0.522]  (0.522, 1.087]  (1.087, 1.651]
0               True             False           False           False
1              False             False           False            True
2               True             False           False           False
3               True             False           False           False
4               True             False           False           False
5               True             False           False           False
6              False             False            True           False
7              False             False           False            True
8              False             False            True           False
9              False              True           False           False