<a href="https://colab.research.google.com/github/Dhinesh-Fedor/C/blob/main/Python_Basics_9(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#numpy
#example

import numpy as np
import sys

a = list(range(100000))
print(sys.getsizeof(100000)*len(a))
b = np.arange(100000)
print(b.size*b.itemsize)


2800000
800000


In [14]:
#NumPy arrays are faster than lists

import time as t

t1 = t.time()
a = range(100000)
b = range(100000)
z = [a[i]+ b[i] for i in range(len(a))]
print(t.time() - t1)

#using numpy
import numpy as np
import time as t

t1 = t.time()
a = np.arange(100000)
b = np.arange(100000)
z = a+b
print(t.time() - t1)



0.03230118751525879
0.0029523372650146484


In [21]:
#creating a numpy array

#1-D array
a = np.array([1,2,3])
b = np.array([(1,2,3)]) #another way
print(a)
print("\n",b)

#2-D array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([(1,2,3),(4,5,6)]) #another way
print("\n",a)
print("\n",b)
print(a.ndim) #prints the dimension
print(a.shape)
print(a[1][2]) #a[rows][cols]



[1 2 3]

 [[1 2 3]]

 [[1 2 3]
 [4 5 6]]

 [[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [26]:
#3-D array

a = np.array([
              [(1,2,3),(4,5,6),(7,8,9)],
              [(1,2,3),(4,5,6),(7,8,9)],
              [(1,2,3),(4,5,6),(7,8,10)],
              ])

print(a)
print("\n",a.shape)
print(a.ndim)
print(a.size) #prints total number of arrays
print(a.itemsize) #prints total number elements in the array
print(a[2][2][2])
print(a[2,2,2])#another way to access elements

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8 10]]]

 (3, 3, 3)
3
27
8
10
10


In [31]:
#Reshaping anarray in numpy
a = np.arange(25)
print(a)

#reshaping
b = a.reshape(5,5)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [38]:
#Ravel a 2D array
#used to get 1D array from 2D array

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.ravel() #converts the 2D array(a) into  1D array
#or b = np.ravel(a) => this also works
print(b)

#flatten() => same function as ravel
a = np.array([[1,2,3],[4,5,6]])
print("\n",a)
b = a.flatten() #converts the 2D array(a) into  1D array
print(b)

#Reshape => same function as ravel
a = np.array([[1,2,3],[4,5,6]])
print("\n",a)
b = a.reshape(-1) #converts the 2D array(a) into  1D array
print(b)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

 [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

 [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [44]:
#Slicing in Numpy
a = np.arange(0,36).reshape(6,6)
print(a)

s = a[3:6,1:4] #a[row_start:row_end,coln_start,coln_end]
print("\n",s)

#Note: end is always n-1

t = a[1:,3:]
print("\n",t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

 [[19 20 21]
 [25 26 27]
 [31 32 33]]

 [[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]


In [53]:
#Built-in Methods

#odd numbers from 101 to 130
a = np.arange(101,130,0.7) #this 0.7 is step value (ie) a(start,end,step)
print(a)

#zeros() => generates arrays with only number of given zeros

#array of 10 zeros
#1D
a = np.zeros(10)
print("\n",a)

#2D
print("\n2d array:")
b = np.zeros([4,4])
print(b)

#3D
print("\n3d array:")
b = np.zeros([4,4,4])
print(b)

#ones() => generates arrays with only number of given ones but type is float

#array of 10 ones
#1D
a = np.ones(10)
print("\n",a)

#2D
print("\n2d array:")
b = np.ones([4,4])
print(b)

#3D
print("\n3d array:")
b = np.ones([4,4,4])
print(b)

[101.  101.7 102.4 103.1 103.8 104.5 105.2 105.9 106.6 107.3 108.  108.7
 109.4 110.1 110.8 111.5 112.2 112.9 113.6 114.3 115.  115.7 116.4 117.1
 117.8 118.5 119.2 119.9 120.6 121.3 122.  122.7 123.4 124.1 124.8 125.5
 126.2 126.9 127.6 128.3 129.  129.7]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

2d array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3d array:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

2d array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3d array:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]

In [66]:
#identity matrix
#np.eye(dimn,dimn,dtype = type) => syntax
#if only one dimn is given then it takes the same value for next dimn and want to change datatype then
#dtype = "type" is passed as a parameter

#examples
a = np.eye(4,3,dtype = int)
print(a)


a = np.eye(4,3,k=-2,dtype = int)
print("\n",a)


#linspace() => print points in terms of linear distribution
a = np.linspace(1,10,20)
print("\n",a)


a = np.linspace(1,10,20,retstep = True) #retstep = True prints the distribution step value
print("\n",a)


[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]

 [[0 0 0]
 [0 0 0]
 [1 0 0]
 [0 1 0]]

 [ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]

 (array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]), 0.47368421052631576)


In [69]:
#logspace() => print points in terms of logarithmic distribution

a = np.logspace(1,10,num = 5,endpoint = True,base = 10.0)
print(a)

a = np.logspace(5,10,num = 5,endpoint = True,base = 10.0)
print("\n",a)

a = np.logspace(5,10,num = 5,endpoint = False,base = 10.0)
print("\n",a)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]

 [1.00000000e+05 1.77827941e+06 3.16227766e+07 5.62341325e+08
 1.00000000e+10]

 [1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]


In [70]:
#Generating random numbers

a = 100000
uniform = np.random.rand(a) #rand =>uniform distribution
normal = np.random.randn(a) #randn => normal distribution
print(uniform)
print(normal)

[0.52851362 0.50500617 0.57758248 ... 0.74177761 0.75518958 0.90095799]
[-0.10615753  0.05861488  0.90412814 ... -0.83283661  0.07040587
  1.51725021]
