<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics_20(Handling%20Missing%20Data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Handling Missing Data Using Pandas

import pandas as pd
import numpy as np

#None as a Sentinel value

a = np.array([1,None,3,4])
a

array([1, None, 3, 4], dtype=object)

In [4]:
%timeit np.array(1E6, dtype=int).sum()

2.06 µs ± 77 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
%timeit np.array(1E6, dtype=object).sum()

2.04 µs ± 60.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
a = np.array([1,None,3,4])
a
a.sum()

#Note:- Aggregate functions would not work with data which has none

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [10]:
#NaN => Mssing Numerical Data

b = np.array([1,np.nan,3,4])
b

array([ 1., nan,  3.,  4.])

In [15]:
b.sum(),b.min(),b.max(),

(nan, nan, nan)

In [11]:
1+np.nan

#Note:- Arithmetic operations will always results in NaN

nan

In [14]:
np.nansum(b),np.nanmax(b),np.nanmin(b),

(8.0, 4.0, 1.0)

In [16]:
#Both NaN and None

c = pd.Series([1,np.nan,None,3,4,5])
c

0    1.0
1    NaN
2    NaN
3    3.0
4    4.0
5    5.0
dtype: float64

In [17]:
d = pd.Series(range(2),dtype = int)
d

0    0
1    1
dtype: int64

In [19]:
d[0] = None
d

0    NaN
1    1.0
dtype: float64

In [23]:
#Pandas Nullabe Dtypes

e =  pd.Series([1,np.nan,None,pd.NA,3,4,5],dtype = 'Int32')
e

0       1
1    <NA>
2    <NA>
3    <NA>
4       3
5       4
6       5
dtype: Int32

In [24]:
f =  pd.Series([1.0,np.nan,None,pd.NA,3.0,4.0,5.0])
f

0     1.0
1     NaN
2    None
3    <NA>
4     3.0
5     4.0
6     5.0
dtype: object

In [28]:
g =  pd.Series([1,np.nan,None,pd.NA,3,4,5],dtype = 'Float32')
g

0     1.0
1    <NA>
2    <NA>
3    <NA>
4     3.0
5     4.0
6     5.0
dtype: Float32

In [29]:
#Operating on Null values

#isnull => returns boolean value on whether null is present or not
#notnull => opposite of isnull
#dropna => filters the data by removing null
#fillna => fills na with some value

In [30]:
h =  pd.Series([1,np.nan,None,pd.NA,3,4,'bob'])
h

0       1
1     NaN
2    None
3    <NA>
4       3
5       4
6     bob
dtype: object

In [33]:
h.isnull()

0    False
1     True
2     True
3     True
4    False
5    False
6    False
dtype: bool

In [34]:
h.notnull()

0     True
1    False
2    False
3    False
4     True
5     True
6     True
dtype: bool

In [35]:
h.dropna()

0      1
4      3
5      4
6    bob
dtype: object

In [36]:
df = pd.DataFrame([
    [1,np.nan,3],
    [4,5,6],
    [np.nan,8,9],
])

df

0    1  2
0  1.0  NaN  3
1  4.0  5.0  6
2  NaN  8.0  9

In [39]:
#column wise dropping
df.dropna(axis=1)

2
0  3
1  6
2  9

In [40]:
#row wise (default)
df.dropna()

0    1  2
1  4.0  5.0  6

In [41]:
df.isnull()

0      1      2
0  False   True  False
1  False  False  False
2   True  False  False

In [43]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  3 NaN
1  4.0  5.0  6 NaN
2  NaN  8.0  9 NaN

In [45]:
df.dropna(axis=1,how = 'all')

0    1  2
0  1.0  NaN  3
1  4.0  5.0  6
2  NaN  8.0  9

In [47]:
df.dropna(thresh=3) #prints row 2 (has 3 not null values)

#Note:- checks for number of not null values

0    1  2   3
1  4.0  5.0  6 NaN

In [48]:
df.dropna(axis=1,thresh=3)

2
0  3
1  6
2  9

In [50]:
#Filling NUll Values

i =  pd.Series([1,np.nan,None,3,4],index = list('abcde'))
i


a    1.0
b    NaN
c    NaN
d    3.0
e    4.0
dtype: float64

In [51]:
#Forward fill

i.fillna(method='ffill')

<ipython-input-51-93c1437399ff>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  i.fillna(method='ffill')


a    1.0
b    1.0
c    1.0
d    3.0
e    4.0
dtype: float64

In [52]:
#Back fill

i.fillna(method='bfill')

<ipython-input-52-2b081fde1004>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  i.fillna(method='bfill')


a    1.0
b    3.0
c    3.0
d    3.0
e    4.0
dtype: float64

In [53]:
#column wise forward fill
df.fillna(axis=1,method='ffill')

<ipython-input-53-37f503cc8615>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(axis=1,method='ffill')


0    1    2    3
0  1.0  1.0  3.0  3.0
1  4.0  5.0  6.0  6.0
2  NaN  8.0  9.0  9.0

In [54]:
#column wise backward fill
df.fillna(axis=1,method='bfill')

<ipython-input-54-66be7d9657fd>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(axis=1,method='bfill')


0    1    2   3
0  1.0  3.0  3.0 NaN
1  4.0  5.0  6.0 NaN
2  8.0  8.0  9.0 NaN

In [55]:
#rowwise forward fill
df.fillna(method='ffill')

<ipython-input-55-cdda7e144d75>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0    1  2   3
0  1.0  NaN  3 NaN
1  4.0  5.0  6 NaN
2  4.0  8.0  9 NaN

In [57]:
#rowwise backward fill
df.fillna(method='bfill')

<ipython-input-57-1a22c1c355b9>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')


0    1  2   3
0  1.0  5.0  3 NaN
1  4.0  5.0  6 NaN
2  NaN  8.0  9 NaN

In [58]:
pd.notnull(b).sum()

3

In [60]:
pd.isnull(b).sum()

1

In [61]:
pd.Series([1,np.nan]).isnull().any()

True

In [62]:
pd.Series([1,2]).isnull().any()

False

In [64]:
i.isnull().values

array([False,  True,  True, False, False])

In [68]:
i.isnull().values.any()

True

In [69]:
i.isnull().values.all()

False